### ISSUE TITLE
tag ?

### ISSUE THREAD

**Issue by mikeSimonson** [weierophinney/changelog_generator#18]
Hi,

Can you tag a new version with the latest few fixes ?

Thanks

**Comment by weierophinney** [comment]
Latest tag is based off the latest commit (v2.1.2)... There are a few PRs I've not merged yet, though - is that what you're asking for?

**Comment by mikeSimonson** [comment]
@weierophinney Sorry it seems that somehow I could only see tag 2.1.1

**Comment by weierophinney** [comment]
I've just tagged 2.2.0 as well: https://github.com/weierophinney/changelog_generator/releases/tag/v2.2.0
